name: advance_math
description: A robust Dart library for comprehensive mathematical programming. Offers expressions, complex numbers, algebra, statistics, angles, and geometry for diverse computations.
version: 5.4.1
repository: https://github.com/gameticharles/advance_math

environment:
  sdk: ^3.4.0

documentation: "https://github.com/gameticharles/advance_math/blob/main/doc/README.md"

dependencies:
  buffer: ^1.2.3
  characters: ^1.4.1
  dartframe: ^0.8.9
  intl: ^0.20.2
  logging: ^1.3.0
  petitparser: ^7.0.1

dev_dependencies:
  test: ^1.28.0
  benchmark_harness: ^2.4.0
  lints: ^6.0.0

topics:
  - translators
  - algebra-matrix-and-calculus
  - statistics
  - geometry
  - expressions
